package session

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/docker/docker-agent/pkg/chat"
)

// generatedImageMessage builds an assistant message shaped like the output
// of runtime.materializeGeneratedMedia: text plus a document part carrying
// only an owner-qualified artifact reference, never inline bytes.
func generatedImageMessage(ownerSessionID string) *Message {
	return &Message{
		Message: chat.Message{
			Role:    chat.MessageRoleAssistant,
			Content: "here is your image",
			MultiContent: []chat.MessagePart{
				{Type: chat.MessagePartTypeText, Text: "here is your image"},
				{
					Type: chat.MessagePartTypeDocument,
					Document: &chat.Document{
						Name:     "cat.png",
						MimeType: "image/png",
						Size:     4,
						Source: chat.DocumentSource{
							ArtifactPath:           "3f9c.png",
							ArtifactRoot:           chat.ArtifactRootWorkspace,
							ArtifactOwnerSessionID: ownerSessionID,
						},
					},
				},
			},
		},
	}
}

// TestGeneratedMediaMessage_PersistsArtifactReferenceNotBytes pins the
// persistence contract: a session containing a generated-media message
// must persist a relative artifact reference and must never contain raw
// image bytes (inline_data) for that part.
func TestGeneratedMediaMessage_PersistsArtifactReferenceNotBytes(t *testing.T) {
	t.Parallel()
	store := openMemoryStore(t)
	ctx := t.Context()

	sess := New(WithID("gen-1"), WithTitle("generated image"))
	require.NoError(t, store.AddSession(ctx, sess))
	_, err := store.AddMessage(ctx, sess.ID, generatedImageMessage(sess.ID))
	require.NoError(t, err)

	raw, err := rawMessagesJSON(t, store, sess.ID)
	require.NoError(t, err)

	assert.Contains(t, raw, `"artifact_path":"3f9c.png"`, "persisted JSON must carry the artifact reference")
	assert.Contains(t, raw, `"artifact_owner_session_id":"gen-1"`, "persisted JSON must carry the owning session ID")
	assert.NotContains(t, raw, `"inline_data"`, "persisted JSON must never carry raw generated bytes")

	got, err := store.GetSession(ctx, sess.ID)
	require.NoError(t, err)
	require.Len(t, got.Messages, 1)
	doc := got.Messages[0].Message.Message.MultiContent[1].Document
	require.NotNil(t, doc)
	assert.Equal(t, "3f9c.png", doc.Source.ArtifactPath)
	assert.Equal(t, "gen-1", doc.Source.ArtifactOwnerSessionID)
	assert.Empty(t, doc.Source.InlineData)
	assert.Equal(t, "here is your image", got.Messages[0].Message.Message.Content, "text must round-trip alongside the artifact reference")
}

// TestWorkspaceGeneratedMediaMessage_RootKindAndPathRoundTrip is the
// persistence contract for workspace-materialized media: the document part
// must persist the workspace root kind and the exact workspace-relative
// path on the wire (artifact_root / artifact_path) and reload identically —
// still without ever carrying inline bytes.
func TestWorkspaceGeneratedMediaMessage_RootKindAndPathRoundTrip(t *testing.T) {
	t.Parallel()
	store := openMemoryStore(t)
	ctx := t.Context()

	sess := New(WithID("ws-1"), WithTitle("workspace generated image"))
	require.NoError(t, store.AddSession(ctx, sess))

	msg := &Message{
		Message: chat.Message{
			Role:    chat.MessageRoleAssistant,
			Content: "here is your image",
			MultiContent: []chat.MessagePart{
				{
					Type: chat.MessagePartTypeDocument,
					Document: &chat.Document{
						Name:     "cat.png",
						MimeType: "image/png",
						Size:     4,
						Source: chat.DocumentSource{
							ArtifactPath:           "images/cat.png",
							ArtifactRoot:           chat.ArtifactRootWorkspace,
							ArtifactOwnerSessionID: sess.ID,
						},
					},
				},
			},
		},
	}
	_, err := store.AddMessage(ctx, sess.ID, msg)
	require.NoError(t, err)

	raw, err := rawMessagesJSON(t, store, sess.ID)
	require.NoError(t, err)
	assert.Contains(t, raw, `"artifact_root":"workspace"`, "persisted JSON must carry the workspace root kind")
	assert.Contains(t, raw, `"artifact_path":"images/cat.png"`, "persisted JSON must carry the exact final relative path")
	assert.NotContains(t, raw, `"inline_data"`, "persisted JSON must never carry raw generated bytes")

	got, err := store.GetSession(ctx, sess.ID)
	require.NoError(t, err)
	require.Len(t, got.Messages, 1)
	doc := got.Messages[0].Message.Message.MultiContent[0].Document
	require.NotNil(t, doc)
	assert.Equal(t, chat.ArtifactRootWorkspace, doc.Source.ArtifactRoot)
	assert.Equal(t, "images/cat.png", doc.Source.ArtifactPath)
	assert.Equal(t, "ws-1", doc.Source.ArtifactOwnerSessionID)
	assert.Empty(t, doc.Source.InlineData)
}

// TestOldSessionWithoutArtifactPath_StillLoads pins backward compatibility:
// a document part serialized before ArtifactPath existed (inline_data only,
// no artifact_path key at all) must still unmarshal cleanly, with
// ArtifactPath defaulting to its zero value.
func TestOldSessionWithoutArtifactPath_StillLoads(t *testing.T) {
	t.Parallel()
	store := openMemoryStore(t)
	ctx := t.Context()

	sess := New(WithID("legacy-doc"), WithTitle("legacy"))
	require.NoError(t, store.AddSession(ctx, sess))

	legacyMsg := &Message{
		Message: chat.Message{
			Role:    chat.MessageRoleUser,
			Content: "here's a screenshot",
			MultiContent: []chat.MessagePart{
				{
					Type: chat.MessagePartTypeDocument,
					Document: &chat.Document{
						Name:     "shot.png",
						MimeType: "image/png",
						Source:   chat.DocumentSource{InlineData: []byte{0x89, 0x50, 0x4e, 0x47}},
					},
				},
			},
		},
	}
	_, err := store.AddMessage(ctx, sess.ID, legacyMsg)
	require.NoError(t, err)

	got, err := store.GetSession(ctx, sess.ID)
	require.NoError(t, err)
	require.Len(t, got.Messages, 1)
	doc := got.Messages[0].Message.Message.MultiContent[0].Document
	require.NotNil(t, doc)
	assert.Empty(t, doc.Source.ArtifactPath, "field absent from legacy JSON must default to empty")
	assert.Equal(t, []byte{0x89, 0x50, 0x4e, 0x47}, doc.Source.InlineData)
}

// TestBranchSession_GeneratedMediaKeepsOwningSessionID is the branch/fork
// regression test for owner-qualified references: BranchSession deep-clones
// the message struct (see cloneSessionItem/cloneMessage), but never copies
// the underlying materialized file. The clone must therefore keep pointing
// at the OWNING (parent) session ID, not whichever session is asking — a
// resolver keyed on the asking session's own (different) ID would silently
// miss.
func TestBranchSession_GeneratedMediaKeepsOwningSessionID(t *testing.T) {
	t.Parallel()

	parent := New(WithID("parent-session"), WithTitle("generated image"))
	parent.AddMessage(UserMessage("draw a cat"))
	parent.AddMessage(generatedImageMessage("parent-session"))

	child, err := BranchSession(parent, len(parent.Messages))
	require.NoError(t, err)
	require.NotEqual(t, parent.ID, child.ID, "branch must mint a fresh session ID")

	childMsgs := child.GetAllMessages()
	require.Len(t, childMsgs, 2)
	doc := childMsgs[1].Message.MultiContent[1].Document
	require.NotNil(t, doc)

	// The clone must keep pointing at the ORIGINAL owner, not the child's
	// own (different) ID — that distinction is the entire point of
	// owner-qualified references.
	assert.Equal(t, "parent-session", doc.Source.ArtifactOwnerSessionID)
	assert.NotEqual(t, child.ID, doc.Source.ArtifactOwnerSessionID)
	assert.Equal(t, "3f9c.png", doc.Source.ArtifactPath, "the relative path must survive the clone unchanged")
}

// TestForkSession_GeneratedMediaKeepsOwningSessionID is the fork-flavored
// counterpart of the branch test above: ForkSession shares the same cloning
// path (branchSessionWithTitle), so the owner qualification must survive
// there too.
func TestForkSession_GeneratedMediaKeepsOwningSessionID(t *testing.T) {
	t.Parallel()

	parent := New(WithID("parent-session-2"), WithTitle("generated image"))
	parent.AddMessage(UserMessage("draw a dog"))
	parent.AddMessage(generatedImageMessage("parent-session-2"))

	child, err := ForkSession(parent, len(parent.Messages))
	require.NoError(t, err)
	require.NotEqual(t, parent.ID, child.ID, "fork must mint a fresh session ID")

	childMsgs := child.GetAllMessages()
	require.Len(t, childMsgs, 2)
	doc := childMsgs[1].Message.MultiContent[1].Document
	require.NotNil(t, doc)
	assert.Equal(t, "parent-session-2", doc.Source.ArtifactOwnerSessionID)
	assert.Equal(t, "3f9c.png", doc.Source.ArtifactPath)
}

// TestBranchSession_PersistedThenBranchedKeepsOwner is the full-fidelity
// round trip: persist the parent to the SQLite store (so the branch is
// reading back real deserialized JSON, not an in-memory struct that
// happens to still hold pointers), branch it, and check the reloaded
// child's reference still names the original owner.
func TestBranchSession_PersistedThenBranchedKeepsOwner(t *testing.T) {
	t.Parallel()
	store := openMemoryStore(t)
	ctx := t.Context()

	parent := New(WithID("persisted-parent"), WithTitle("generated image"))
	require.NoError(t, store.AddSession(ctx, parent))
	_, err := store.AddMessage(ctx, parent.ID, UserMessage("draw a cat"))
	require.NoError(t, err)
	_, err = store.AddMessage(ctx, parent.ID, generatedImageMessage(parent.ID))
	require.NoError(t, err)

	reloadedParent, err := store.GetSession(ctx, parent.ID)
	require.NoError(t, err)

	child, err := BranchSession(reloadedParent, len(reloadedParent.Messages))
	require.NoError(t, err)
	require.NoError(t, store.AddSession(ctx, child))

	childMsgs := child.GetAllMessages()
	require.Len(t, childMsgs, 2)
	doc := childMsgs[1].Message.MultiContent[1].Document
	require.NotNil(t, doc)
	assert.Equal(t, "persisted-parent", doc.Source.ArtifactOwnerSessionID)
	assert.Equal(t, "3f9c.png", doc.Source.ArtifactPath)
}

// rawMessagesJSON returns the raw session_items.message_json for every
// message row belonging to sessionID, letting the test assert on wire
// format directly rather than through the round-tripped Go struct (which
// would mask a mistaken field name or an accidental inline-bytes leak).
func rawMessagesJSON(t *testing.T, store *SQLiteSessionStore, sessionID string) (string, error) {
	t.Helper()
	rows, err := store.db.QueryContext(t.Context(),
		`SELECT message_json FROM session_items WHERE session_id = ? AND item_type = 'message'`, sessionID)
	if err != nil {
		return "", err
	}
	defer rows.Close()

	var all []byte
	for rows.Next() {
		var data string
		if err := rows.Scan(&data); err != nil {
			return "", err
		}
		// Round-trip through json to normalize key order/whitespace so the
		// substring assertions above are not fragile to formatting.
		var v any
		if err := json.Unmarshal([]byte(data), &v); err != nil {
			return "", err
		}
		normalized, err := json.Marshal(v)
		if err != nil {
			return "", err
		}
		all = append(all, normalized...)
	}
	return string(all), rows.Err()
}
