package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/dgageot/rubocop-go/config"
	"github.com/dgageot/rubocop-go/cop"
	"github.com/dgageot/rubocop-go/coptest"
	"github.com/dgageot/rubocop-go/prog"
	"github.com/dgageot/rubocop-go/runner"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestAdditionalSharedFileCopScopes(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		name, src string
		frozen    bool
	}{
		{"ContextFirstParameter", `import "context"
func f(n int, ctx context.Context) {}`, false},
		{"NoContextField", `import "context"
type service struct { ctx context.Context }`, false},
		{"HTTPRequestWithContext", `import "net/http"
func f() { _, _ = http.NewRequest("GET", "/", nil) }`, false},
		{"NoFatalOutsideMain", `import "log"
func f() { log.Fatal("failed") }`, true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			c := registeredSharedCop(t, cops, "Lint/"+tc.name)
			for _, path := range []string{"pkg/config/v0/sample.go", "pkg/config/v15/sample.go", "pkg/config/latest/sample.go", "notpkg/config/v0/sample.go", "pkg/generated/sample.go", "pkg/sample_test.go"} {
				src := "package p\n" + tc.src
				if strings.Contains(path, "generated") {
					src = "// Code generated by fixture; DO NOT EDIT.\n" + src
				}
				want := 1
				if strings.HasSuffix(path, "_test.go") || (!tc.frozen && frozenConfigPath.MatchString(path)) {
					want = 0
				}
				assert.Len(t, coptest.RunNamed(t, c, path, src), want, path)
			}
			if tc.name == "NoFatalOutsideMain" {
				assert.Empty(t, coptest.Run(t, c, "package main\n"+tc.src))
			}
		})
	}
}

func TestAdditionalSharedProgramCopsRunner(t *testing.T) {
	for _, tc := range []struct {
		name, minimum, older, src string
	}{
		{"ErrorsAsType", "1.26", "1.25", `import "errors"
type E struct{}
func (*E) Error() string { return "e" }
func f(err *E) { var e *E; if errors.As(err, &e) { println(e) } }`},
		{"MapsCopy", "1.21", "1.20", `func f(dst, src map[string]int) { for k, v := range src { dst[k] = v } }`},
		{"MapsClone", "1.21", "1.20", `func f(src map[string]int) map[string]int {
	if src == nil { return nil }; dst := make(map[string]int, len(src))
	for k, v := range src { dst[k] = v }; return dst
}`},
		{"SlicesContains", "1.21", "1.20", `func f(xs []int, n int) bool {
	for _, v := range xs { if v == n { return true } }; return false
}`},
		{"SlicesEqual", "1.21", "1.20", `func f(a, b []int) bool {
	if len(a) != len(b) { return false }
	for i := range a { if a[i] != b[i] { return false } }; return true
}`},
		{"SplitSeq", "1.24", "1.23", `import "strings"
func f(s string) { for _, part := range strings.Split(s, "/") { println(part) } }`},
		{"SortedMapKeys", "1.23", "1.22", `import "sort"
func f(src map[string]int) []string {
	var keys []string; for k := range src { keys = append(keys, k) }; sort.Strings(keys); return keys
}`},
		{"WaitGroupGo", "1.25", "1.24", `import "sync"
func f() { var wg sync.WaitGroup; wg.Add(1); go func() { defer wg.Done(); println("work") }(); wg.Wait() }`},
		{"HTTPTestRequestWithContext", "1.23", "1.22", `import ("context"; "net/http"; "net/http/httptest")
func f(ctx context.Context) *http.Request { return httptest.NewRequest("GET", "/", nil).WithContext(ctx) }`},
	} {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			t.Chdir(dir)
			id := "Lint/" + tc.name
			var want []string
			for _, path := range []string{
				"pkg/config/v0/sample.go", "pkg/config/v15/sample.go", "pkg/config/latest/sample.go",
				"pkg/config/version/sample.go", "notpkg/config/v0/sample.go", "generated/sample.go",
				"internal/sample_test.go", "external/sample_test.go", "testonly/sample_test.go",
				"inline/sample.go", "suppressed/sample.go", "inactive/sample.go", "oldlanguage/sample.go", "illtyped/sample_test.go",
			} {
				src := "package p\n" + tc.src
				switch {
				case strings.HasPrefix(path, "generated/"):
					src = "// Code generated by fixture; DO NOT EDIT.\n" + src
				case strings.HasPrefix(path, "external/"):
					src = strings.Replace(src, "package p", "package p_test", 1)
				case strings.HasPrefix(path, "inline/"):
					src = strings.ReplaceAll(src, "\n", " //rubocop:disable "+id+"\n")
					src += " //rubocop:disable " + id + "\n"
				case strings.HasPrefix(path, "suppressed/"):
					src = "//rubocop:disable-file " + id + "\n" + src
				case strings.HasPrefix(path, "inactive/"):
					src = "//go:build lint_fixture_disabled\n\n" + src
				case strings.HasPrefix(path, "oldlanguage/"):
					if tc.name != "SplitSeq" {
						continue
					}
					src = "//go:build go1.22\n\n" + src
				case strings.HasPrefix(path, "illtyped/"):
					src += "\nvar _ = missing\n"
				}
				require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o700))
				require.NoError(t, os.WriteFile(path, []byte(src), 0o600))
				if strings.HasPrefix(path, "internal/") || strings.HasPrefix(path, "external/") || strings.HasPrefix(path, "illtyped/") {
					require.NoError(t, os.WriteFile(filepath.Join(filepath.Dir(path), "empty.go"), []byte("package p\n"), 0o600))
				}
				if strings.HasPrefix(path, "pkg/config/latest/") || strings.HasPrefix(path, "pkg/config/version/") || strings.HasPrefix(path, "notpkg/") || (strings.HasSuffix(path, "_test.go") && !strings.HasPrefix(path, "illtyped/")) {
					want = append(want, path)
				}
			}
			cfg := config.DefaultConfig()
			cfg.Cops[id] = config.CopConfig{Severity: "warning"}
			c := registeredSharedCop(t, programCops, id)
			for _, version := range []string{tc.older, tc.minimum, "1.27"} {
				require.NoError(t, os.WriteFile("go.mod", []byte("module example.test\n\ngo "+version+"\n"), 0o600))
				var output bytes.Buffer
				r := runner.New(nil, cfg, &output).WithProgramCops([]prog.Cop{c})
				r.Reporter = runner.NewJSONReporter(&output)
				count, err := r.Run([]string{"."})
				require.NoError(t, err)
				if version == tc.older {
					assert.Zero(t, count, output.String())
					continue
				}
				assert.Equal(t, len(want), count, output.String())
				var report struct {
					Offenses []struct{ Cop, File, Severity string }
				}
				require.NoError(t, json.Unmarshal(output.Bytes(), &report))
				var got []string
				for _, offense := range report.Offenses {
					assert.Equal(t, id, offense.Cop)
					assert.Equal(t, "warning", offense.Severity)
					file, err := filepath.Rel(dir, offense.File)
					require.NoError(t, err)
					got = append(got, filepath.ToSlash(file))
				}
				assert.ElementsMatch(t, want, got, version)
			}
		})
	}
}

func TestAdditionalSharedFileCopSuppressions(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)
	const src = `package p
import ("context"; "log"; "net/http")
//rubocop:disable Lint/NoContextField // Owns the lifecycle.
type service struct { ctx context.Context }
//rubocop:disable Lint/ContextFirstParameter // Preserve the public signature.
func New(n int, ctx context.Context) {}
func request() { _, _ = http.NewRequest("GET", "/", nil) } //rubocop:disable Lint/HTTPRequestWithContext
func fatal() { log.Fatal("failed") } //rubocop:disable Lint/NoFatalOutsideMain
`
	require.NoError(t, os.WriteFile("sample.go", []byte(src), 0o600))
	var selected []cop.Cop
	for _, name := range []string{"ContextFirstParameter", "NoContextField", "HTTPRequestWithContext", "NoFatalOutsideMain"} {
		selected = append(selected, registeredSharedCop(t, cops, "Lint/"+name))
	}
	var output bytes.Buffer
	count, err := runner.New(selected, config.DefaultConfig(), &output).Run([]string{"."})
	require.NoError(t, err)
	assert.Zero(t, count, output.String())
}
