package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"testing"

	"github.com/dgageot/rubocop-go/config"
	"github.com/dgageot/rubocop-go/cop"
	"github.com/dgageot/rubocop-go/coptest"
	"github.com/dgageot/rubocop-go/prog"
	"github.com/dgageot/rubocop-go/runner"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestSharedCopRegistrations(t *testing.T) {
	t.Parallel()
	require.Len(t, cops, 29)
	require.Len(t, programCops, 19)
	counts := make(map[string]int)
	for _, c := range cops {
		counts[c.Name()]++
	}
	for _, c := range programCops {
		counts[c.Name()]++
	}
	assert.Len(t, counts, 48)
	for name, count := range counts {
		assert.Equal(t, 1, count, name)
	}
	for _, name := range []string{
		"SlogContextual", "ConstructorPurity", "ConstructorNetworkIO", "WrapErrors",
		"ErrorStringMatching", "DeferMutexUnlock", "NewExpr",
	} {
		registeredSharedCop(t, cops, "Lint/"+name)
	}
	for _, name := range []string{
		"PointerHelper", "ReflectFields", "StdlibUUID", "URLClone", "JSONMarshalWrite",
		"BenchmarkLoop", "SplitTrimJoin", "FieldsSeq", "StreamCloseSafety", "SlicesClone", "SlicesConcat",
	} {
		registeredSharedCop(t, programCops, "Lint/"+name)
	}
}

func TestSharedProgramCopScopes(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		name, src string
		scoped    bool
	}{
		{"ReflectFields", `import "reflect"
func fields(v reflect.Value) {
	for i := range v.NumField() { _ = v.Field(i).Interface(); _ = v.Type().Field(i).Tag.Get("json") }
}`, true},
		{"URLClone", `import "net/url"
func clone(u *url.URL) *url.URL {
	if u == nil { return nil }; c := *u
	if u.User != nil { user := *u.User; c.User = &user }; return &c
}`, true},
		{"JSONMarshalWrite", `import ("bytes"; "encoding/json"; "strings")
func encode(v any) (string, error) {
	var buf bytes.Buffer; enc := json.NewEncoder(&buf)
	if err := enc.Encode(v); err != nil { return "", err }; return strings.TrimSuffix(buf.String(), "\n"), nil
}`, true},
		{"FieldsSeq", `import "strings"
func words(s string) { for range strings.Fields(s) {} }`, false},
		{"SplitTrimJoin", `import "strings"
func trim(s string) string {
	parts := strings.Split(s, "/")
	for len(parts) > 1 && parts[len(parts)-1] == "" { parts = parts[:len(parts)-1] }; return strings.Join(parts, "/")
}`, false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			files := coptest.ProgramFiles{"go.mod": "module example.test\n\ngo 1.27\n", "tests/empty.go": "package p\n"}
			var want []string
			for _, dir := range []string{"pkg/config/v0", "pkg/config/v15", "pkg/config/latest", "pkg/config/version", "notpkg/config/v0", "generated", "tests"} {
				name, src := dir+"/sample.go", "package p\n"+tc.src
				if dir == "generated" {
					src = "// Code generated by fixture; DO NOT EDIT.\n" + src
				}
				if dir == "tests" {
					name = dir + "/sample_test.go"
				} else if !tc.scoped || (dir != "pkg/config/v0" && dir != "pkg/config/v15" && dir != "generated") {
					want = append(want, name)
				}
				files[name] = src
			}
			var got []string
			offenses := coptest.RunProgram(t, registeredSharedCop(t, programCops, "Lint/"+tc.name), files)
			require.Len(t, offenses, len(want))
			for _, o := range offenses {
				assert.Equal(t, "Lint/"+tc.name, o.CopName)
				for name := range files {
					if strings.HasSuffix(filepath.ToSlash(o.Pos.Filename), "/"+name) {
						got = append(got, name)
					}
				}
			}
			assert.ElementsMatch(t, want, got)
		})
	}
}

func TestSharedDependencyCopScopes(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		name, module, dependency, path, declaration, call string
	}{
		{"PointerHelper", "github.com/aws/aws-sdk-go-v2", "aws", "aws/pointer.go", "func String(s string) *string { return &s }", `sdk.String("x")`},
		{"StdlibUUID", "github.com/google/uuid", "uuid", "uuid.go", `func NewString() string { return "id" }`, "sdk.NewString()"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			importPath := tc.module
			if tc.name == "PointerHelper" {
				importPath += "/aws"
			}
			files := coptest.ProgramFiles{
				"go.mod":                "module example.test\n\ngo 1.27\nrequire " + tc.module + " v0.0.0\nreplace " + tc.module + " => ./dependency\n",
				"dependency/go.mod":     "module " + tc.module + "\n\ngo 1.27\n",
				"dependency/" + tc.path: "package " + tc.dependency + "\n" + tc.declaration,
			}
			for _, dir := range []string{"pkg/config/v0", "pkg/config/v15", "pkg/config/latest", "generated"} {
				src := "package p\nimport sdk " + strconv.Quote(importPath) + "\nvar value = " + tc.call
				if dir == "generated" {
					src = "// Code generated by fixture; DO NOT EDIT.\n" + src
				}
				files[dir+"/sample.go"] = src
			}
			offenses := coptest.RunProgram(t, registeredSharedCop(t, programCops, "Lint/"+tc.name), files)
			require.Len(t, offenses, 1)
			assert.True(t, strings.HasSuffix(filepath.ToSlash(offenses[0].Pos.Filename), "/pkg/config/latest/sample.go"))
		})
	}
}

func TestSharedCopsRunner(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)
	require.NoError(t, os.WriteFile("go.mod", []byte("module example.test\n\ngo 1.27\n"), 0o600))
	const src = `package p
import ("strings"; "testing")
func pointer() *int { v := 42; return &v }
func words(s string) { for range strings.Fields(s) {} }
func match(err error) bool { return strings.Contains(err.Error(), "missing") }
func BenchmarkProduction(b *testing.B) { b.ResetTimer(); for range b.N {} }
`
	const tests = `package p
import ("strings"; "testing")
func testPointer() *int { v := 42; return &v }
func testMatch(err error) bool { return strings.Contains(err.Error(), "missing") }
func BenchmarkWork(b *testing.B) { b.ResetTimer(); for range b.N {} }
`
	var want []string
	for _, tc := range []struct {
		dir, prefix                          string
		newExpr, matching, fields, benchmark bool
	}{
		{"pkg/config/v0", "", false, false, true, false},
		{"pkg/config/v15", "", false, false, true, false},
		{"pkg/config/latest", "", true, true, true, true},
		{"pkg/config/version", "", true, true, true, true},
		{"notpkg/config/v0", "", true, true, true, true},
		{"generated", "// Code generated by fixture; DO NOT EDIT.\n", false, true, true, false},
		{"inline", "", false, false, false, false},
		{"suppressed", "//rubocop:disable-file Lint/NewExpr, Lint/ErrorStringMatching, Lint/FieldsSeq, Lint/BenchmarkLoop\n", false, false, false, false},
	} {
		require.NoError(t, os.MkdirAll(tc.dir, 0o700))
		for name, content := range map[string]string{"sample.go": src, "sample_test.go": tests} {
			if tc.dir == "inline" {
				content = strings.ReplaceAll(content, " }\n", " } //rubocop:disable Lint/NewExpr, Lint/ErrorStringMatching, Lint/FieldsSeq, Lint/BenchmarkLoop\n")
			}
			require.NoError(t, os.WriteFile(filepath.Join(tc.dir, name), []byte(tc.prefix+content), 0o600))
		}
		for name, enabled := range map[string]bool{"NewExpr": tc.newExpr, "ErrorStringMatching": tc.matching, "FieldsSeq": tc.fields, "BenchmarkLoop": tc.benchmark} {
			if enabled {
				file := "sample.go"
				if name == "BenchmarkLoop" {
					file = "sample_test.go"
				}
				want = append(want, "Lint/"+name+":"+tc.dir+"/"+file)
				if name == "NewExpr" {
					want = append(want, "Lint/NewExpr:"+tc.dir+"/sample_test.go")
				}
			}
		}
	}
	cfg := config.DefaultConfig()
	for _, name := range []string{"NewExpr", "ErrorStringMatching", "FieldsSeq", "BenchmarkLoop"} {
		cfg.Cops["Lint/"+name] = config.CopConfig{Severity: "convention"}
	}
	var output bytes.Buffer
	r := runner.New([]cop.Cop{registeredSharedCop(t, cops, "Lint/NewExpr"), registeredSharedCop(t, cops, "Lint/ErrorStringMatching")}, cfg, &output).
		WithProgramCops([]prog.Cop{registeredSharedCop(t, programCops, "Lint/FieldsSeq"), registeredSharedCop(t, programCops, "Lint/BenchmarkLoop")})
	r.Reporter = runner.NewJSONReporter(&output)
	count, err := r.Run([]string{"."})
	require.NoError(t, err)
	assert.Equal(t, len(want), count, output.String())
	var report struct {
		Offenses []struct{ Cop, File, Severity string }
	}
	require.NoError(t, json.Unmarshal(output.Bytes(), &report))
	var got []string
	for _, o := range report.Offenses {
		assert.Equal(t, "convention", o.Severity)
		name := o.File
		if filepath.IsAbs(name) {
			name, err = filepath.Rel(dir, name)
			require.NoError(t, err)
		}
		got = append(got, o.Cop+":"+strings.TrimPrefix(filepath.ToSlash(name), "./"))
	}
	assert.ElementsMatch(t, want, got)
}

func registeredSharedCop[T interface{ Name() string }](t *testing.T, registered []T, name string) T {
	t.Helper()
	i := slices.IndexFunc(registered, func(c T) bool { return c.Name() == name })
	require.NotEqual(t, -1, i, "missing registered cop %s", name)
	return registered[i]
}
