package runtime

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path"
	"path/filepath"
	"strings"
	"unicode/utf8"

	"github.com/docker/docker-agent/pkg/chat"
	"github.com/docker/docker-agent/pkg/tools"
	"github.com/docker/docker-agent/pkg/workspacemedia"
)

// generatedMediaItem carries the per-item context needed to route one
// generated media blob through the naming and workspace-escape policy.
type generatedMediaItem struct {
	workspaceRoot string
	// requestedPath is the prompt-directed target (untrusted marker or
	// user-prompt input, see chat.MediaDelta.RequestedPath); empty when
	// nothing named the blob explicitly.
	requestedPath string
	// providerName is the sanitized provider display name; genericName the
	// deterministic "generated-N" fallback.
	providerName string
	genericName  string
	data         []byte
	// mimeType is the raw provider MIME (the writer derives the extension
	// from it); safeMimeType the sanitized form for anything user-visible.
	mimeType     string
	safeMimeType string
	agentName    string
	sessionID    string
	index, total int
}

// generatedMediaWrite is the outcome of a routed write: the writer result
// plus the artifact root kind its RelPath is interpreted against.
type generatedMediaWrite struct {
	res  workspacemedia.Result
	root chat.ArtifactRootKind
}

// writeGeneratedMedia writes one generated media item according to the
// approved escape policy: a prompt-directed workspace-relative path is
// honored directly; an absolute/traversing/home-rooted path is refused
// unless the user explicitly confirms the resolved external target via a
// runtime-native elicitation; a declined, cancelled, unanswerable, or
// invalid request redirects the bytes to the workspace root under the
// sanitized basename — already-generated bytes are never discarded solely
// because the requested path escaped. Without a prompt-directed path the
// provider display name (then the generic name) is used, as before.
func (r *LocalRuntime) writeGeneratedMedia(ctx context.Context, item generatedMediaItem, events EventSink) (generatedMediaWrite, error) {
	if item.requestedPath == "" {
		return r.writeProviderNamedMedia(item)
	}

	class, cleaned := workspacemedia.ClassifyRequestedPath(item.requestedPath)
	switch class {
	case workspacemedia.PathWorkspaceRelative:
		res, err := workspacemediaWrite(item.workspaceRoot, cleaned, item.data, item.mimeType)
		if err != nil && errors.Is(err, workspacemedia.ErrPathEscape) {
			// Lexically contained but escaping at I/O time (a symlinked
			// parent directory): same policy as an unconfirmed escape.
			return r.redirectEscapedMedia(item, events, "escapes the workspace")
		}
		return generatedMediaWrite{res: res, root: chat.ArtifactRootWorkspace}, err
	case workspacemedia.PathEscaping:
		target, confirmable := externalMediaTarget(item.workspaceRoot, item.requestedPath, item.externalDirFilename())
		if confirmable && r.confirmMediaEscape(ctx, target, item) {
			res, err := workspacemediaWriteExternal(target, item.data, item.mimeType)
			return generatedMediaWrite{res: res, root: chat.ArtifactRootExternal}, err
		}
		return r.redirectEscapedMedia(item, events, "is outside the workspace and was not confirmed")
	default:
		return r.redirectEscapedMedia(item, events, "is not a usable path")
	}
}

// externalDirFilename is the filename used when the confirmed external
// target is an existing directory: the provider display name (then the
// generic fallback) with the exact extension the writer would give it, so
// the user confirms the full final path, not a bare directory.
func (item generatedMediaItem) externalDirFilename() string {
	name := item.providerName
	if name == "" {
		name = item.genericName
	}
	return workspacemedia.DefaultFilename(name, item.mimeType)
}

// writeProviderNamedMedia is the pre-existing no-explicit-name flow: the
// sanitized provider display name, then the generic name.
func (r *LocalRuntime) writeProviderNamedMedia(item generatedMediaItem) (generatedMediaWrite, error) {
	requested := item.providerName
	if requested == "" {
		requested = item.genericName
	}
	res, err := workspacemediaWrite(item.workspaceRoot, requested, item.data, item.mimeType)
	if err != nil && requested != item.genericName && errors.Is(err, workspacemedia.ErrPathEscape) {
		// A provider display name the writer refuses even after display
		// sanitization (e.g. a Windows-reserved name like "CON.png") must
		// not cost the user the item; there is no user-chosen path to
		// honor at this stage, so fall back to the generic name.
		res, err = workspacemediaWrite(item.workspaceRoot, item.genericName, item.data, item.mimeType)
	}
	return generatedMediaWrite{res: res, root: chat.ArtifactRootWorkspace}, err
}

// redirectEscapedMedia lands a refused prompt-directed item in the
// workspace root under the requested path's basename (generic fallback) and
// emits a sanitized warning explaining the redirect. The warning names only
// the final written path — never the requested one, a raw error, or any
// reference internals.
func (r *LocalRuntime) redirectEscapedMedia(item generatedMediaItem, events EventSink, reason string) (generatedMediaWrite, error) {
	base := workspacemedia.RequestedBasename(item.requestedPath)
	if base == "" {
		base = item.genericName
	}
	res, err := workspacemediaWrite(item.workspaceRoot, base, item.data, item.mimeType)
	if err != nil && base != item.genericName && errors.Is(err, workspacemedia.ErrPathEscape) {
		res, err = workspacemediaWrite(item.workspaceRoot, item.genericName, item.data, item.mimeType)
	}
	if err != nil {
		return generatedMediaWrite{}, err
	}
	if events != nil {
		warning := fmt.Sprintf("Requested save location for generated media item %d/%d %s; saved as %s in the workspace instead",
			item.index, item.total, reason, res.RelPath)
		events.Emit(Warning(chat.TruncateUTF8Bytes(warning, maxPlaceholderOrWarningBytes), item.agentName))
	}
	return generatedMediaWrite{res: res, root: chat.ArtifactRootWorkspace}, nil
}

// mediaEscapeElicitationTitle is surfaced via the event meta key
// "cagent/title", which the TUI elicitation dialog uses as its title.
const mediaEscapeElicitationTitle = "Save outside the workspace?"

// The escape confirmation is a schema-backed form so accepting is an
// explicit act: the safe "keep in workspace" choice is listed first, making
// it every form client's default selection — a bare submit (Enter in the
// TUI) yields the decline choice, never an external write. The runtime
// additionally verifies the submitted value, so a permissive client that
// accepts with empty or free-form content still cannot authorize the write.
const (
	// MediaEscapeDecisionField is the single required property of
	// [MediaEscapeDecisionSchema].
	MediaEscapeDecisionField = "decision"
	// MediaEscapeAcceptChoice is the only MediaEscapeDecisionField value
	// that authorizes writing outside the workspace.
	MediaEscapeAcceptChoice = "Save outside the workspace"
	// MediaEscapeDeclineChoice keeps the file in the workspace; listed
	// first in the enum so it is the default selection.
	MediaEscapeDeclineChoice = "Keep it in the workspace"
)

// MediaEscapeDecisionSchema is the requested schema attached to the
// workspace-escape confirmation elicitation. Exported so client surfaces
// (e.g. the TUI elicitation dialog tests) can prove how they interpret
// this exact schema.
func MediaEscapeDecisionSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			MediaEscapeDecisionField: map[string]any{
				"type":        "string",
				"title":       "Decision",
				"description": fmt.Sprintf("Only an explicit %q writes outside the workspace.", MediaEscapeAcceptChoice),
				"enum":        []any{MediaEscapeDeclineChoice, MediaEscapeAcceptChoice},
			},
		},
		"required": []any{MediaEscapeDecisionField},
	}
}

// confirmMediaEscape asks the user to confirm writing one generated media
// item to target, through the same waiter registry and ResumeElicitation
// plumbing as MCP elicitations. Only an explicit accept counts: decline,
// cancel, a cancelled ctx, non-interactive mode, and headless background
// sessions (auto-declined inside requestElicitation, so the stream is never
// blocked with nobody to answer) all return false.
func (r *LocalRuntime) confirmMediaEscape(ctx context.Context, target string, item generatedMediaItem) bool {
	message := fmt.Sprintf(
		"Agent %q wants to save generated media (%s, item %d/%d) OUTSIDE the workspace, at: %s — choose %q to write it there; otherwise it is kept in the workspace under a safe name.",
		item.agentName, item.safeMimeType, item.index, item.total, target, MediaEscapeAcceptChoice,
	)
	result, err := r.requestElicitation(ctx, elicitationSpec{
		message:   message,
		mode:      "form",
		schema:    MediaEscapeDecisionSchema(),
		meta:      map[string]any{"cagent/title": mediaEscapeElicitationTitle},
		agentName: item.agentName,
		sessionID: item.sessionID,
	})
	if err != nil {
		slog.DebugContext(ctx, "Workspace-escape confirmation was not answered; redirecting into the workspace",
			"agent", item.agentName, "session_id", item.sessionID, "error", err)
		return false
	}
	if result.Action != tools.ElicitationActionAccept {
		return false
	}
	// Accept alone is not enough: the submitted form must carry the exact
	// affirmative choice, so a bare/empty accept (e.g. Enter on a free-form
	// prompt in an older client) can never authorize an external write.
	choice, _ := result.Content[MediaEscapeDecisionField].(string)
	return choice == MediaEscapeAcceptChoice
}

// externalMediaTarget resolves an escaping requested path to the absolute
// target the user will be asked to confirm: separators normalized, a
// leading "~" expanded to the home directory, and a relative traversal
// anchored at the workspace root. ok is false when no faithfully
// displayable target can be derived — an unexpandable "~user" prefix,
// control characters, invalid UTF-8, or an over-long path — because the
// user must never be asked to confirm something other than the exact path
// that would be written. A target that resolves to an existing directory
// means "save inside it": dirFilename (the generated filename, extension
// included) is appended before confirmation, so accepting a directory can
// never produce a dash-suffixed sibling of that directory.
func externalMediaTarget(workspaceRoot, requested, dirFilename string) (target string, ok bool) {
	p := filepath.FromSlash(strings.ReplaceAll(requested, `\`, `/`))
	if rest, isHome := strings.CutPrefix(p, "~"); isHome {
		if rest != "" && !strings.HasPrefix(rest, string(filepath.Separator)) {
			return "", false
		}
		home, err := os.UserHomeDir()
		if err != nil {
			return "", false
		}
		p = filepath.Join(home, rest)
	}
	if !filepath.IsAbs(p) {
		p = filepath.Join(workspaceRoot, p)
	}
	p = filepath.Clean(p)
	if info, err := os.Stat(p); err == nil && info.IsDir() {
		p = filepath.Join(p, dirFilename)
	}
	return p, displayableEscapeTarget(p)
}

// displayableEscapeTarget reports whether p can appear verbatim in the
// confirmation prompt: valid UTF-8, no control characters, bounded like
// every other user-visible generated-media string.
func displayableEscapeTarget(p string) bool {
	if len(p) > maxPlaceholderOrWarningBytes || !utf8.ValidString(p) {
		return false
	}
	for _, r := range p {
		if r < 0x20 || r == 0x7f {
			return false
		}
	}
	return true
}

// generatedDocumentName derives the display name for a written item:
// workspace paths are slash-separated, external ones OS-native.
func generatedDocumentName(root chat.ArtifactRootKind, finalPath string) string {
	if root == chat.ArtifactRootExternal {
		return filepath.Base(finalPath)
	}
	return path.Base(finalPath)
}

// workspacemediaWriteExternal is [workspacemedia.WriteExternal] behind the
// same test-only indirection as workspacemediaWrite (see loop.go).
// Production code must never reassign it.
var workspacemediaWriteExternal = workspacemedia.WriteExternal
