package chat

// MessagePartTypeDocument is the part type for a structured document attachment.
// Use this type when attaching files (images, PDFs, text, Office docs, etc.) to
// a message. The Document field must be set when this type is used.
//
// This supersedes MessagePartTypeFile and MessagePartTypeImageURL, which are
// deprecated but remain supported for backward compatibility.
const MessagePartTypeDocument MessagePartType = "document"

// ArtifactRootKind identifies which root a DocumentSource.ArtifactPath is
// relative to.
type ArtifactRootKind string

// ArtifactRootWorkspace means ArtifactPath is relative to the OWNING
// session's workspace root (the session's effective WorkingDir, resolved
// via session.ResolveWorkingDir) — generated media lands in the user's
// workspace as an ordinary visible file, written by pkg/workspacemedia.
//
// An empty ArtifactRoot marks a reference whose root is unknown; such a
// reference is never resolved and surfaces as unavailable.
const ArtifactRootWorkspace ArtifactRootKind = "workspace"

// DocumentSource holds the actual content of a document. Exactly one of the
// fields should be set.
type DocumentSource struct {
	// InlineText holds the raw text for text/* MIME types (TXT, MD, HTML, CSV, …).
	// Used for StrategyTXT attachments.
	InlineText string `json:"inline_text,omitempty"`

	// InlineData holds binary content (images, PDFs, Office docs, …) that is
	// base64-encoded when sent to the provider. Used for StrategyB64 attachments.
	InlineData []byte `json:"inline_data,omitempty"`

	// ArtifactPath references binary content that was generated by a model
	// (not user-attached) and materialized to disk instead of being kept
	// inline, so session JSON never carries generated bytes. It is
	// interpreted against the root selected by ArtifactRoot:
	//
	//   - ArtifactRootWorkspace: relative, slash-separated — never absolute,
	//     never containing ".." — resolved against the owning session's
	//     workspace root, exactly as returned by workspacemedia.Write.
	//   - empty: the root is unknown — never resolved; the part surfaces
	//     as unavailable.
	ArtifactPath string `json:"artifact_path,omitempty"`

	// ArtifactRoot is the root kind ArtifactPath is relative to. See
	// ArtifactRootWorkspace; empty means the root is unknown and the
	// reference is unresolvable.
	ArtifactRoot ArtifactRootKind `json:"artifact_root,omitempty"`

	// ArtifactOwnerSessionID is the ID of the session the artifact was
	// materialized under — always the session active at generation time,
	// which never changes even after the message is copied into a branched
	// or forked session. Resolving ArtifactPath under the CURRENT session
	// instead of this owner is exactly the bug this field exists to prevent:
	// branching/forking clones message structs (see pkg/session/branch.go)
	// but never copies the materialized files themselves, so a lookup keyed
	// on the current session ID silently misses once the message is viewed
	// from anywhere but the original session.
	//
	// Empty on any non-media document part. Resolution treats an ownerless
	// media reference as unavailable rather than guessing a session to look
	// under.
	ArtifactOwnerSessionID string `json:"artifact_owner_session_id,omitempty"`
}

// Document represents a file attachment in a message part. It carries
// the file name, post-processing MIME type, and the actual content via Source.
//
// The MimeType field always reflects the final MIME that the attachment system
// will use when sending to the provider (e.g. "image/jpeg" after image
// normalisation, never the original "image/bmp").
type Document struct {
	// Name is the display name of the document (e.g. "report.pdf").
	Name string `json:"name"`

	// MimeType is the post-processing MIME type of the document. For images
	// this is always "image/jpeg" or "image/png" regardless of the original
	// format. For text files it is the exact MIME (e.g. "text/plain",
	// "text/markdown", "text/html"). For binary documents it is the original
	// MIME (e.g. "application/pdf").
	MimeType string `json:"mime_type"`

	// Size is the byte length of the document content (InlineData or InlineText).
	// Optional; zero means unknown.
	Size int64 `json:"size,omitempty"`

	// Source holds the actual document content.
	Source DocumentSource `json:"source"`
}
