package chat

// MediaDelta carries binary media generated by a provider while a response
// is streaming (e.g. an inline image blob from Gemini). It is the shared,
// provider-agnostic representation for this content: adapters for any
// provider populate it the same way, and the runtime accumulator is the only
// consumer, so no provider gets a side channel of its own.
//
// Data holds the live bytes only for the duration of the stream. Once the
// turn completes, the runtime materializes them into a session artifact and
// the persisted assistant message keeps only a reference — see
// [DocumentSource.ArtifactPath]. Data is never written to session storage.
type MediaDelta struct {
	// Data is the raw generated bytes. Present only on the streaming delta;
	// never persisted.
	Data []byte `json:"data,omitempty"`

	// MimeType is the media's MIME type as reported by the provider (e.g.
	// "image/png").
	MimeType string `json:"mime_type,omitempty"`

	// Name is the provider-supplied display name, if any. May be empty; the
	// runtime accumulator synthesizes one when needed.
	Name string `json:"name,omitempty"`

	// RequestedPath is the prompt-directed target path for this blob, when
	// one exists. It is untrusted input: the runtime routes it through
	// workspacemedia.ClassifyRequestedPath, and a path escaping the workspace
	// requires an explicit user confirmation before it is honored. The
	// runtime's response marker filter (the "[media-file: ...]" protocol,
	// pkg/runtime/generated_media_markers.go) populates it by pairing marker
	// paths with blobs in response order; a single otherwise-unnamed blob may
	// instead get it from deterministic explicit-filename extraction on the
	// triggering user message (pkg/runtime/generated_media_prompt_filename.go).
	// Blobs neither source names keep it empty and materialization falls back
	// to Name, then a generic name.
	RequestedPath string `json:"requested_path,omitempty"`

	// Size is the byte length of Data, cached because Data itself is
	// dropped once the artifact is materialized.
	Size int64 `json:"size,omitempty"`
}
