package chat

// MediaDelta carries complete provider-generated bytes through the internal
// stream accumulator. It is not a persisted assistant-message representation
// or a progressive binary presentation event.
type MediaDelta struct {
	// Data is the complete provider-generated payload.
	Data []byte `json:"data,omitempty"`

	// MimeType is the media's MIME type as reported by the provider (e.g.
	// "image/png").
	MimeType string `json:"mime_type,omitempty"`

	// Name is an optional provider-supplied display hint, not a trusted path.
	// Materialization chooses a fallback when no usable name is available.
	Name string `json:"name,omitempty"`

	// RequestedPath is untrusted. Marker paths take precedence; prompt-filename
	// fallback applies only to exactly one returned image without a marker.
	// Materialization redirects paths outside the workspace to a sanitized
	// workspace basename. Empty paths use the provider name, then a generic name.
	RequestedPath string `json:"requested_path,omitempty"`

	// Size is the byte length of Data for downstream metadata.
	Size int64 `json:"size,omitempty"`
}
