package chat

// MediaDelta carries binary media generated by a provider while a response
// is streaming (e.g. an inline image blob from Gemini). It is the shared,
// provider-agnostic representation for this content: adapters for any
// provider populate it the same way, and the runtime accumulator is the only
// consumer, so no provider gets a side channel of its own.
//
// Data holds the live bytes only for the duration of the stream. Once the
// turn completes, the runtime materializes them into a session artifact and
// the persisted assistant message keeps only a reference — see
// [DocumentSource.ArtifactPath]. Data is never written to session storage.
type MediaDelta struct {
	// Data is the raw generated bytes. Present only on the streaming delta;
	// never persisted.
	Data []byte `json:"data,omitempty"`

	// MimeType is the media's MIME type as reported by the provider (e.g.
	// "image/png").
	MimeType string `json:"mime_type,omitempty"`

	// Name is the provider-supplied display name, if any. May be empty; the
	// runtime accumulator synthesizes one when needed.
	Name string `json:"name,omitempty"`

	// Size is the byte length of Data, cached because Data itself is
	// dropped once the artifact is materialized.
	Size int64 `json:"size,omitempty"`
}
